# Default values for tmc-proto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tmcprototype:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmcprototype
    tag: 424-recoverability
    pullPolicy: Always

tmalarmhandler:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmalarmhandler
    tag: latest
    pullPolicy: Always

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: latest
    pullPolicy: IfNotPresent

tmcdb:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmcstatedb
    tag: latest
    pullPolicy: Always
  db:
    rootpw: secret
    db: tmc_recoverability
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

nodeSelector: {}

affinity: {}

tolerations: []
