apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  apm-server.yml: |
    apm-server:
        host: "0.0.0.0:8200"
    queue: {}
    output.elasticsearch:
        hosts: ["http://elastic-{{ template "logging.name" . }}-{{ .Release.Name }}:9200"]

