apiVersion: v1
kind: Pod
metadata:
 name: demo-logproducer-{{ template "logging.fullname" . }}-{{ .Release.Name }}
 namespace: {{ .Release.Namespace }}
spec:
 containers:
 - name: stdout-logproducer
   image: centos:7
   command:
     - "bin/bash"
     - "-c"
     - |
        while true; do echo "1|$(date "+%Y-%m-%dT%T.%6NZ")|DEBUG||demo.stdout.logproducer|logproducer.py#1|tango-device:my/dev/name|A log line from stdout." | tee /dev/stderr; sleep 1; done