{{ if .Values.elastic.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      initContainers:
      - name: setdatadirpermissions
        image: "{{ .Values.elastic.image.registry }}/{{ .Values.elastic.image.image }}:{{ .Values.elastic.image.tag }}"
        imagePullPolicy: {{ .Values.elastic.image.pullPolicy }}
        command:
          - sh
          - -c
          - 'chown 1000:1000 /usr/share/elasticsearch/data' 
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data

      containers:
      - name: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
        image: "{{ .Values.elastic.image.registry }}/{{ .Values.elastic.image.image }}:{{ .Values.elastic.image.tag }}"
        imagePullPolicy: {{ .Values.elastic.image.pullPolicy }}
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          exec:
            command:
            - '/bin/sh'
            - '-c'
            - |
              /bin/bash <<EOF
              curl -X PUT "localhost:9200/_ilm/policy/logstash-policy?pretty" -H 'Content-Type: application/json' -d\
              '{
              "policy" : {
                  "phases" : {
                  "hot" : {
                      "min_age" : "0ms",
                      "actions" : {
                      "rollover" : {
                          "max_size" : "100mb",
                          "max_age" : "1h",
                          "max_docs" : 150000
                      }
                      }
                  },
                  "delete" : {
                      "min_age" : "2h",
                      "actions" : {
                      "delete" : { }
                      }
                  }
                  }
                  }
              }'
              EOF

          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: elastic-data
        persistentVolumeClaim:
          claimName: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200

{{ end }}