{{ if .Values.elastic.enabled }}

{{ if .Values.elastic.use_pv }}
{{ if .Values.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
    chart: {{ template "logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/elastic-{{ template "logging.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}/
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: elastic-{{ template "logging.name" . }}-{{ .Release.Name }}
    chart: {{ template "logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  resources:
    requests:
      storage: 10Gi
{{ if .Values.minikube }}
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
  - ReadWriteMany
{{ end }}

{{ end }} # use_pv

{{ end }} # enabled
