apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config-map-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  ska_log_parsing_pipeline.json: |
    {
      "description" : "SKA log parsing pipeline",
      "processors" : [
        {
          "grok": {
            "field": "log",
            "ignore_failure": true,
            "patterns": ["%{INT:ska_version}\\|%{DATA:ska_log_timestamp}\\|%{DATA:ska_severity}\\|%{DATA:ska_thread_id}\\|%{DATA:ska_function}\\|%{DATA:ska_line_loc}\\|%{DATA:ska_tags}\\|%{DATA:ska_log_message}$"]
          }
        }
      ]
    }

  ska_ilm_policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_size": "1gb",
                "max_age": "1d"
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "delete": {
            "min_age": "1d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }

  ska_index_template.json: |
    {
      "index_patterns": ["log*"],
      "settings": {
        "index": {
          "lifecycle": {
            "name": "ska_ilm_policy",
            "rollover_alias": "log*"
          },
          "number_of_shards": "1",
          "number_of_replicas": "1",
          "default_pipeline": "ska_log_parsing_pipeline"
        }
      },
      "mappings": {
        "properties": {
          "kubernetes": {
            "properties": {
              "container_image_id": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "container_name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "namespace_id": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "host": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "master_url": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "pod_id": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "container_image": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "labels": {
                "properties": {
                  "component": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "controller-revision-hash": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "job-name": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "pod-template-generation": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "pod-template-hash": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "run": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "version": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "controller-uid": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "k8s-app": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "kubernetes_io/cluster-service": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  }
                }
              },
              "namespace_name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              },
              "pod_name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              }
            }
          },
          "kubernetes_namespace": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            }
          },
          "@timestamp": {
            "type": "date"
          },
          "log": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            }
          },
          "stream": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            }
          },
          "tag": {
            "type": "text",
            "fields": {
              "keyword": {
                "ignore_above": 256,
                "type": "keyword"
              }
            }
          },
          "docker": {
            "properties": {
              "container_id": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                }
              }
            }
          }
        }
      },
      "aliases": {}
    }
  