apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  ska.conf: |
    # journald
    <filter docker.systemd>
      @type kubernetes_metadata
      use_journal true
    </filter>

    <match kubelet>
      @type null
    </match>

    <match bootkube>
      @type null
    </match>

    <filter docker.systemd>
      @type record_transformer
      enable_ruby true
      <record>
        kubernetes_namespace ${record["kubernetes"]["namespace_name"]}
      </record>
    </filter>

    <filter docker.systemd>
      @type grep
      <regexp>
        key kubernetes_namespace
        pattern /{{ .Release.Namespace }}/
      </regexp>
    </filter>


    # syslog
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        kubernetes_namespace ${record["kubernetes"]["namespace_name"]}
      </record>
    </filter>

    <filter kubernetes.**>
      @type grep
      <regexp>
        key kubernetes_namespace
        pattern /{{ .Release.Namespace }}/
      </regexp>
    </filter>
