# Default values for csp-proto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

midcbfmcs:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mid-cbf-mcs
    tag: 0.2.1
    pullPolicy: IfNotPresent

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.2.5.1
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
