image: nexus.engageska-portugal.pt/ska-docker/deploy:0.3.0

stages:
  - problem

.pip_install_test_requirements: &pip_install_test_requirements |-
  pip3 install -r test-requirements.txt

in-cluster-problem:
  stage: problem
  tags:
    - docker-executor
  before_script:
    - kubectl create ns tmp
    - echo "192.168.93.47   kubernetes.engageska-portugal.pt" >> /etc/hosts
  script:
    - kubectl run -n tmp tmp-pod --restart=Never --image=busybox --wait -- /bin/sh -c 'sleep 300'
    - kubectl exec -n tmp tmp-pod -- /bin/sh -c 'uname -r && ps aux'
  after_script:
    - kubectl delete ns tmp
  environment:
    name: test

