image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

stages:
  - lint
  - clean
  - deploy
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

clean test: 
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  environment:
    name: test
  only:
    refs:
      - schedules

clean staging: 
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=staging
  environment:
    name: staging
  only:
    refs:
      - schedules

deploy test:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt
  - kubectl get all,pv,pvc,ingress -n integration
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  only:
    refs:
      - master

deploy staging:
  stage: deploy
  tags:
  - docker-executor
  script:  
  - make deploy_all KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt
  - kubectl get all,pv,pvc,ingress -n staging
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  only:
    refs:
      - staging

clean test: 
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  environment:
    name: test
  when: manual
