image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

variables:
  debug_before_stages: "deploy"
  debug_before_cmd: "kubectl get all --all-namespaces"
  debug_after_stages: "deploy"
  debug_after_cmd: ""

default:
  before_script: 
  - "(echo $DEBUG_BEFORE_STAGES | grep -q $CI_JOB_STAGE) && $DEBUG_BEFORE_CMD"
  after_script: 
  - "(echo $DEBUG_AFTER_STAGES | grep -q $CI_JOB_STAGE) && $DEBUG_AFTER_CMD"

stages:
  - lint
  - clean
  - deploy
  - test
  -  debug
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test environment:
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=sarao HELM_RELEASE=sarao
  - kubectl delete namespace sarao
  environment:
    name: test
  only:
    variables:
      - $DELETE == "true"

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao
  - kubectl get all,pv,pvc,ingress -n sarao
  retry: 2
  environment:
    name: test

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao && [ -f "build/report.xml" ]
  environment:
    name: test
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml
  allow_failure: true

print-debug-info:
  stage: debug
  variables:
    DEBUG_CMD: echo noop
  tags:
  - docker-executor
  script:
  - /bin/sh -exc "$DEBUG_CMD"
  - kubectl describe ingresses --all-namespaces
  - kubectl describe -n kube-system pod $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - kubectl logs --tail=100 -n kube-system  $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - kubectl logs --tail=100 -n sarao deployment.apps/logstash-deployment-logging-sarao
  - kubectl logs --tail=100 -n sarao deployment.apps/kibana-logging-sarao
  - kubectl logs --tail=100 -n sarao deployment.apps/elastic-logging-sarao
  - kubectl logs --tail=100 -n integration $(kubectl get pod -n integration   | grep fluentd | head -n 1  | cut -d\  -f1)
  - exit 42
  environment:
    name: test
  when: manual
  allow_failure: true

delete-and-deploy test environment:
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=sarao HELM_RELEASE=sarao
  - make deploy_all KUBE_NAMESPACE=sarao INGRESS_HOST=sarao.engageska-portugal.pt HELM_RELEASE=sarao
  - kubectl describe ingresses --all-namespaces
  - kubectl describe -n kube-system pod $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - sleep 5m 
  - kubectl logs -n kube-system  $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1)
  - kubectl logs -n sarao deployment.apps/logstash-deployment-logging-sarao
  - kubectl logs -n sarao deployment.apps/kibana-logging-sarao
  - kubectl logs -n sarao deployment.apps/elastic-logging-sarao
  environment:
    name: test
  when: manual
