image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

stages:
  - lint
  - clean
  - deploy
  - test
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test environment:
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  environment:
    name: test
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

delete staging environment: 
  stage: clean
  retry: 2
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=staging HELM_RELEASE=staging
  environment:
    name: staging
  only:
    refs:
      - staging
    variables:
      - $DELETE == "true"

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - if [ -n "$HELM_CHART" ]; then make delete KUBE_NAMESPACE=integration; fi;
  - make deploy_all KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt
  - kubectl get all,pv,pvc,ingress -n integration
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  only:
    refs:
      - master

deploy staging environment:
  stage: deploy
  retry: 2
  tags:
  - docker-executor
  script:  
  - make deploy_all KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging
  - kubectl get all,pv,pvc,ingress -n staging
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  only:
    refs:
      - staging

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt && [ -d "build/report.xml" ]
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  only:
    refs:
      - master
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

k8s_test staging environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:  
  - make k8s_test KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging && [ -d "build/report.xml" ]
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  only:
    refs:
      - staging
  artifacts:
    name: "report.json"
    paths: ['build/report.json']
    reports:
      junit: build/report.xml

delete-and-deploy test environment:
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  - make deploy_all KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  when: manual
  only:
    refs:
      - master

delete-and-deploy staging environment: 
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=staging HELM_RELEASE=staging
  - make deploy_all KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  when: manual
  only:
    refs:
      - staging
