image: nexus.engageska-portugal.pt/ska-docker/deploy:0.4.0

variables:
  DEPLOY_ENVIRONMENT: "test"
  CT_TEST_ENVIRONMENT: "test"
  KUBE_NAMESPACE: "integration"
  INGRESS_HOST: "integration.engageska-portugal.pt"
  DEPLOY_URL: "http://integration.engageska-portugal.pt/testdb"
  HELM_TILLER_SILENT: "true"
  HELM_TILLER_LOGS: "true"

stages:
  - static_analysis
  - unit_test
  - clean
  - deploy
  - test
  - post_test
  - debug

.pip_install_test_requirements: &pip_install_test_requirements |-
  pip3 install -r test-requirements.txt

.teardown_k8s_test_resources: &teardown_k8s_test_resources |-
  kubectl delete all --all --namespace=ci-$CI_JOB_ID --force --grace-period=0 || true
  kubectl delete namespace ci-$CI_JOB_ID || true
  helm ls | grep -E '(FAILED|DELETED)' | awk '{print $1}' | xargs -I'%N' helm delete --purge \%N

before_script: 
  - export HELM_TILLER_LOGS_DIR=$PWD/tiller.log

helm-lint:
  stage: static_analysis
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

ct-lint:
  stage: static_analysis
  tags:
  - docker-executor
  allow_failure: true
  variables:
    PYTHONIOENCODING: utf8
  script:
  - ct lint --config ci/ct.yaml --all

.helm-template-tests:
  stage: static_analysis
  tags:
  - docker-executor
  allow_failure: false
  script:
  - make template_tests

helm-template-pytest:
  stage: static_analysis
  tags:
  - docker-executor
  allow_failure: false
  script:
  - *pip_install_test_requirements
  - pytest -m no_deploy --test-namespace=ci-$CI_JOB_ID
  artifacts:
    when: always
    name: template-pytest-reports
    paths:
    - junit-report.xml
    - pytest-logs.txt
    reports:
      junit: junit-report.xml

.ct-test:
  stage: test
  tags:
  - docker-executor
  allow_failure: true
  script:
  - ct install --config ci/ct.yaml --release-label $CI_COMMIT_REF_SLUG --build-id $CI_JOB_ID --namespace ct-test-$CI_JOB_ID
  after_script:
    - kubectl delete namespace ct-test-$CI_JOB_ID || true
  artifacts:
    when: always
    paths:
    - tiller.log
  environment:
    name: $CT_TEST_ENVIRONMENT

chart-pytest:
  stage: test
  tags:
    - docker-executor
  allow_failure: true
  before_script:
    - *pip_install_test_requirements
  script:
    - pytest -m "chart_deploy and not quarantine" --use-tiller-plugin --test-namespace=ci-$CI_JOB_ID || [ "$?" == "5" ] && true
  after_script:
    - *teardown_k8s_test_resources
  environment:
    name: $CT_TEST_ENVIRONMENT
  artifacts:
    when: always
    name: chart-pytest-reports
    paths:
    - junit-report.xml
    - pytest-logs.txt
    - tiller.log
    reports:
      junit: junit-report.xml

.chart-pytest-quarantine:
  stage: test
  tags:
    - docker-executor
  allow_failure: true
  before_script:
    - *pip_install_test_requirements
  script:
    - pytest -m quarantine --use-tiller-plugin --test-namespace=ci-$CI_JOB_ID || true
  after_script:
    - *teardown_k8s_test_resources
  environment:
    name: $CT_TEST_ENVIRONMENT
  artifacts:
    when: always
    name: chart-pytest-reports
    paths:
      - junit-report.xml
      - pytest-logs.txt
    reports:
      junit: junit-report.xml

delete test environment:
  stage: clean
  retry: 2
  tags:
  - docker-executor
  script:
  - make delete_all || true
  - kubectl delete all --all -n $KUBE_NAMESPACE
  - kubectl delete namespace $KUBE_NAMESPACE
  - kubectl delete namespace $KUBE_NAMESPACE-sdp
  environment:
    name: $DEPLOY_ENVIRONMENT
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

deploy test environment:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all 
  - kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
  retry: 2
  environment:
    name: $DEPLOY_ENVIRONMENT
    url: $DEPLOY_URL
  only:
    refs:
      - master

k8s_test test environment:
  stage: test
  retry: 2
  tags:
  - docker-executor
  script:
  - make k8s_test && [ -f "build/report.xml" ]
  environment:
    name: $DEPLOY_ENVIRONMENT
    url: $DEPLOY_URL
  only:
    refs:
      - master
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths: 
      - "build/"
    reports:
      junit: build/report.xml
    when: always

smoketest test environment:
  stage: test
  tags:
  - docker-executor
  script:
  - make smoketest
  environment:
    name: $DEPLOY_ENVIRONMENT
    url: $DEPLOY_URL
  only:
    refs:
      - master

.run-debug-cmd:
  stage: debug
  variables:
    DEBUG_CMD: echo noop
  tags:
  - docker-executor
  script:
  - /bin/sh -exc "$DEBUG_CMD"
  when: manual
  allow_failure: true

print-debug-info:
  stage: debug
  when: always
  tags:
  - docker-executor
  script:
  - mkdir .public
  - kubectl describe ingresses --all-namespaces > .public/ingresses-all-namespaces.txt
  - kubectl describe -n kube-system pod $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1) > .public/describe-traefik.txt
  - kubectl logs --tail=100 -n kube-system  $(kubectl get pod -n kube-system | grep traefik | cut -d\  -f1) > .public/logs-traefik.txt
  - make podlogs > .public/podlogs.txt
  - kubectl logs --tail=100 -n $KUBE_NAMESPACE $(kubectl get pod -n $KUBE_NAMESPACE | grep fluentd | head -n 1  | cut -d\  -f1) > .public/fluentd.txt
  - kubectl get all --all-namespaces > .public/get-all-namespaces.txt
  - mv .public public
  environment:
    name: $DEPLOY_ENVIRONMENT
  artifacts:
    paths:
    - public

xray_report:
  stage: post_test
  tags:
  - docker-executor
  script:
    - 'curl -X POST -H "Content-type: application/json" --fail
         -H "Authorization: Basic $JIRA_AUTH"
         --data @build/cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  when: always
  only: [master]
  retry: 2
