image: nexus.engageska-portugal.pt/ska-docker/deploy:latest

stages:
  - lint
  - clean
  - deploy
  - lifecycle

lint:
  stage: lint
  tags:
  - docker-executor
  allow_failure: true
  script:
  - make lint_all

delete test: 
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  environment:
    name: test
  only:
    refs:
      - master
    variables:
      - $DELETE == "true"

delete staging: 
  stage: clean
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=staging HELM_RELEASE=staging
  environment:
    name: staging
  only:
    refs:
      - staging
    variables:
      - $DELETE == "true"

deploy test:
  stage: deploy
  tags:
  - docker-executor
  script:
  - make deploy_all KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt
  - kubectl get all,pv,pvc,ingress -n integration
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  only:
    refs:
      - master

deploy staging:
  stage: deploy
  tags:
  - docker-executor
  script:  
  - make deploy_all KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging
  - kubectl get all,pv,pvc,ingress -n staging
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  only:
    refs:
      - staging

delete-and-deploy test: 
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=integration
  - make deploy_all KUBE_NAMESPACE=integration INGRESS_HOST=integration.engageska-portugal.pt
  environment:
    name: test
    url: http://integration.engageska-portugal.pt/testdb
  when: manual
  only:
    refs:
      - master

delete-and-deploy staging: 
  stage: lifecycle
  tags:
  - docker-executor
  script:
  - make delete_all KUBE_NAMESPACE=staging
  - make deploy_all KUBE_NAMESPACE=staging INGRESS_HOST=kubernetes.engageska-portugal.pt HELM_RELEASE=staging
  environment:
    name: staging
    url: http://kubernetes.engageska-portugal.pt/testdb
  when: manual
  only:
    refs:
      - staging
