elastic:
  enabled: false
fluentd:
  enabled: false
kibana:
  enabled: false
tests:
  enabled: false
hdbppdb:
  enabled: false
archiver:
  enabled: false

minikube: false

pv:
  storageClassName: cinder-csi
