apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying the DSH LMC prototype on Kubernetes
name: dsh-lmc-prototype
version: 0.5.3
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
