# Default values for dsh-lmc-prototype.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Pull secrets to add for protected registries - uncomment and adjust:
#
# pullSecrets:
#   - gitlab-registry
#
# and create pull secrets eg:
# kubectl create secret -n <KUBE_NAMESPACE> \
#        docker-registry <PULL_SECRET> \
#        --docker-server=<REGISTRY> \
#        --docker-username=<REGISTRY_USER> \
#        --docker-password=<REGISTRY_PASSWORD> \
#        --docker-email=<USER_EMAIL>

# Only enable Helm tests when using Tiller
helmTests: true

dshlmc:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-telescope
    image: dsh_lmc_prototype
    tag: 0.1.0
    pullPolicy: IfNotPresent
  db:
    db: tango
    user: tango
    password: tango

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.2.5.1
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
