{{if .Values.enabled}}
{{if .Values.non_interactive}} {{else}}
---
apiVersion: v1
kind: Service
metadata:
 name: acceptance-testing-service
 namespace: {{ .Release.Namespace }}
 labels: 
  app: {{ .Values.app}}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
spec:
 type: NodePort
 ports:
 - port: 2022
   name: "ssh" 
   targetPort: 22
   protocol: TCP
 - port: 8888
   name: "jupyter" 
   targetPort: 8888 
 selector:
    app: {{ .Values.app}}
    non_interactive: "{{ .Values.non_interactive}}"
{{end}}

---
apiVersion: v1
kind: Pod
metadata: 
 name: {{ .Values.pod_name}}
 namespace: {{ .Release.Namespace }}
 labels:
   app: {{ .Values.app}}
   release: {{ .Release.Name }}
   heritage: {{ .Release.Service }}
   non_interactive: "{{ .Values.non_interactive}}"
spec:
 volumes:
  - name: environment
    configMap:
      name: ssh-configmap-oet-{{ .Release.Name }}  {{if .Values.non_interactive}} {{else}}
  - name: testing-folder
    persistentVolumeClaim:
      claimName: {{ .Values.pvc }}  {{end}}
 containers:
 - name: sshcheck
   image: {{ .Values.oet.image.registry }}/{{ .Values.oet.image.name }}:{{ .Values.oet.image.tag }}
   imagePullPolicy: Always 
   workingDir: {{ .Values.source_code}}
   ports:
    - containerPort: 22
   env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
   volumeMounts:
      - name: ssh-configmap-volume
          mountPath: /home/tango/.profile
          subPath: .profile
      - name: ssh-configmap-volume
          mountPath: /etc/environment
          subPath: environment
      - name: testing-folder 
        mountPath: {{ .Values.source_code }} {{end}}
 restartPolicy: Always
 {{end}}

