---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "tango-configuration-json-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}"
data: 
  configuration.json: 
{{ (tpl (.Files.Glob "data/configuration.json").AsConfig . ) | indent 2  }}

---
apiVersion: v1
kind: Pod
metadata:
  name: dsconfig-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dsconfig-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
    - name: configuration
      configMap:
        name: "tango-configuration-json-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}"

  containers:
  - name: dsconfig
    image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
    imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000
      - --timeout=30
      - --strict
      - --
      - json2tango -w -a data/configuration.json
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000
    volumeMounts:
      - name: configuration
        mountPath: data
        readOnly: true

  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

