---
suite: fluentd unit tests
templates:
  - fluentd-daemonset.yaml
  - fluentd-config-map.yaml
  - fluentd-rbac.yaml
tests:
  - it: name should conform to naming convention 
    release:
      name: any-helm-release
    asserts:
      - equal:
          path: metadata.name
          value: fluentd-logging-any-helm-release

