{{ if .Values.rbac.enabled }}

{{ range .Values.namespaces }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .name }}
  name: {{ .name }}-others
rules:
- apiGroups: ["*"]
  resources: ["etcdclusters"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .name }}
  name: {{ .name }}-others-binding
subjects:
{{ range .users }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: Role
  name: {{ .name }}-others
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ .name }}
subjects:
{{ range .users }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: ClusterRole 
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-sdp-binding
  namespace: {{ .name }}-sdp 
subjects:
{{ range .users }}
- kind: User
  name: {{ . }} 
  apiGroup: rbac.authorization.k8s.io
{{ end }}
roleRef:
  kind: ClusterRole 
  name: admin
  apiGroup: rbac.authorization.k8s.io

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: sdp-binding
#   namespace: sdp
# subjects:
# {{ range .users }}
# - kind: User
#   name: {{ . }}
#   apiGroup: rbac.authorization.k8s.io
# {{ end }}
# roleRef:
#   kind: ClusterRole 
#   name: admin
#   apiGroup: rbac.authorization.k8s.io

{{ end }}
{{ end }}
