{{ if .Values.tmcdb.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "tmc-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: state-port
    port: 3306
  clusterIP: None
  selector:
    app: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "tmc-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
  serviceName: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
        chart: {{ template "tmc-proto.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
        image: "{{ .Values.tmcdb.image.registry }}/{{ .Values.tmcdb.image.image }}:{{ .Values.tmcdb.image.tag }}"
        imagePullPolicy: {{ .Values.tmcdb.image.pullPolicy }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ .Values.tmcdb.db.rootpw }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.tmcdb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tmcdb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tmcdb.db.password }}"
          - name: MYSQL_HOST
            value: "staterecover-tmc-proto-{{.Release.Name}}"
        ports:
        - name: state-port
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
{{ toYaml .Values.tmcdb.resources | indent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: staterecover-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}
