{{ if .Values.tangodb.enabled }}

{{ if .Values.tangodb.use_pv }}
{{ if .Values.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tangodb-{{ template "tango-base.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}/
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tangodb-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{ if .Values.minikube }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 1Gi
{{ end }}

{{ end }}