{{ if .Values.vscode.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: vscodeport
    port: 22
    protocol: TCP
    nodePort: {{ .Values.vscode.nodeport }}
  selector:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
    chart: {{ template "tango-base.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  serviceName: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
  replicas:  {{ .Values.vscode.replicas }}
  template:
    metadata:
      labels:
        app: vscode-{{ template "tango-base.name" . }}-{{ .Release.Name }}
        chart: {{ template "tango-base.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: vscode
        image: "{{ .Values.vscode.image.registry }}/{{ .Values.vscode.image.image }}:{{ .Values.vscode.image.tag }}"
        imagePullPolicy: {{ .Values.vscode.image.pullPolicy }}
        ports:
        - name: vscodeport
          containerPort: 22
        env:
        - name: KUBE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE
          value: {{ .Release.Name }}
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000 
        resources:
{{ toYaml .Values.vscode.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}