# Default values for HDB++ Archiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

archiver:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: archiver
    tag: latest
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: hdbpp
    user: tango
    passowrd: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

hdbppdb:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: mariadb_hdbpp
    tag: latest
    pullPolicy: Always
  db:
    rootpw: secret
    db: hdbpp
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: latest
    pullPolicy: IfNotPresent

confighdbpp:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: latest
    pullPolicy: IfNotPresent

hdbppviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: hdbpp-viewer
    tag: latest
    pullPolicy: Always

attrconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: ska-python-buildenv
    tag: 0.1.0
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
