{{ if .Values.skuid.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skuid-deployment-{{ template "skuid.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      run: skuid-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        run: skuid-{{ .Release.Namespace }}
    spec:
      containers:
      - name: skuid-{{ template "skuid.name" . }}-{{ .Release.Name }}
        envFrom:
        - configMapRef:
            name: skuid-config-{{ template "skuid.name" . }}-{{ .Release.Name }}
            optional: false
        image: "{{ .Values.skuid.image.registry }}/{{ .Values.skuid.image.image }}:{{ .Values.skuid.image.tag }}"
        imagePullPolicy: {{ .Values.skuid.image.pullPolicy }}
        ports:
        - name: skuid-http
          containerPort: 9870
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 9870
          initialDelaySeconds: 5
          timeoutSeconds: 10
        volumeMounts:
        {{ if .Values.skuid.use_pv }}
        - name: skuid-data
          mountPath: {{ .Values.skuid.config.data_dir }}
        {{ end }}
        {{ if .Values.skuid.config.entity_types.override }}
        - name: skuid-config
          mountPath: {{ .Values.skuid.config.config_dir }}
        {{ end }}

      volumes:
      {{ if .Values.skuid.use_pv }}
      - name: skuid-data
        persistentVolumeClaim:
          claimName: skuid-pvc-{{ .Release.Namespace }}-{{ .Release.Name }}
      {{ end }}
      {{ if .Values.skuid.config.entity_types.override }}
      - name: skuid-config
        configMap:
          name: skuid-config-{{ template "skuid.name" . }}-{{ .Release.Name }}
      {{ end }}
---

apiVersion: v1
kind: Service
metadata:
  name: skuid-{{ template "skuid.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    service: skuid-{{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    run: skuid-{{ .Release.Namespace }}
  ports:
  - port: {{ .Values.skuid.service_port }}
    targetPort: 9870

{{ end }}
