{{ if .Values.skuid.enabled }}

{{ if .Values.skuid.use_pv }}
{{ if .Values.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: skuid-pv-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: skuid-{{ .Release.Namespace }}-{{ .Release.Name }}
    chart: {{ template "skuid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/skuid-{{ template "skuid.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}/
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skuid-pvc-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: skuid-{{ template "skuid.name" . }}-{{ .Release.Name }}
    chart: {{ template "skuid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{ if .Values.minikube }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 100Mi

{{ end }} # use_pv

{{ end }} # enabled
