{{ if .Values.webjive.enabled }}
{{ if .Values.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-{{ template "webjive.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-{{ template "webjive.name" . }}-{{ .Release.Name }}
    chart: {{ template "webjive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-{{ template "webjive.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}/
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-{{ template "webjive.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-{{ template "webjive.name" . }}-{{ .Release.Name }}
    chart: {{ template "webjive.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{ if .Values.minikube }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 10Gi

{{ end }}