{{ if .Values.dshlmc.enabled }}

{{- $chart_name := .Chart.Name -}}

{{- $release_namespace := .Release.Namespace -}}
{{- $release_name := .Release.Name -}}
{{- $release_service := .Release.Service -}}

{{- $dsh_lmc_prototype_name :=  default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}

{{- $image_reg := .Values.dshlmc.image.registry -}}
{{- $image_image := .Values.dshlmc.image.image -}}
{{- $image_tag := .Values.dshlmc.image.tag -}}
{{- $image_pull_policy := .Values.dshlmc.image.pullPolicy -}}

{{- $ds_image_reg := .Values.dsconfig.image.registry -}}
{{- $ds_image_image := .Values.dsconfig.image.image -}}
{{- $ds_image_tag := .Values.dsconfig.image.tag -}}

{{- $db_db := .Values.dshlmc.db.db -}}
{{- $db_user := .Values.dshlmc.db.user -}}
{{- $db_password := .Values.dshlmc.db.password -}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: "dshlmc-configuration-json-{{ $dsh_lmc_prototype_name }}-{{ $release_name }}"
  namespace: {{ $release_namespace }}
data:
  configuration.json:
{{ (tpl (.Files.Glob "data/configuration.json").AsConfig . ) | indent 2  }}

{{- range .Values.dshlmc.dishes }}
---

apiVersion: v1
kind: Pod
metadata:
  name: {{ $dsh_lmc_prototype_name }}-{{ $release_name }}-{{ . }}
  namespace: {{ $release_namespace }}
  labels:
    app: dshlmc-{{ $dsh_lmc_prototype_name }}-{{ $release_name }}
    chart: {{ $dsh_lmc_prototype_name }}
    release: {{ $release_name }}
    heritage: {{ $release_service }}
spec:
  volumes:
  - name: configuration
    configMap:
      name: "dshlmc-configuration-json-{{ $dsh_lmc_prototype_name }}-{{ $release_name }}"
  initContainers:
  - name: dsconfig-init-{{ . }}
    image: "{{ $ds_image_reg }}/{{ $ds_image_image }}:{{ $ds_image_tag }}"
    imagePullPolicy: IfNotPresent
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-tango-base-{{ $release_name }}:10000
      - --timeout=30
      - --strict
      - --
      - json2tango -w -a -u data/configuration.json
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ $release_name }}:10000
    volumeMounts:
    - name: configuration
      mountPath: data
      readOnly: true

  containers:
    - name: dish-master-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/dish-master {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: ds-simulator-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/ds-simulator {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: dsctrl-simulator-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/dsctrl-simulator {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: lmc-logger-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/lmc-logger {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: pdu-manager-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "sleep infinity"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: pdu-simulator-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/pdu-simulator {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: rx-simulator-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/rx-simulator {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

    - name: spf-simulator-{{ . }}
      image: "{{ $image_reg }}/{{ $image_image }}:{{ $image_tag }}"
      imagePullPolicy: {{ $image_pull_policy }}
      command:
        - sh
      args:
        - -c
        - "./bin/spf-simulator {{ . }}"
      env:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ $release_name }}:10000

  {{- end }}

{{ end }}