{{ if .Values.dshlmc.enabled }}

---
apiVersion: v1
kind: Pod
metadata:
  name: dsh-lmc-prototype-{{ template "dsh-lmc-prototype.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dshlmc-{{ template "dsh-lmc-prototype.name" . }}-{{ .Release.Name }}
    chart: {{ template "dsh-lmc-prototype.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.pullSecrets }}
  imagePullSecrets:
  {{- range .Values.pullSecrets }}
    - name: {{ . }}
  {{- end}}
  {{- end }}

  initContainers:
  - name: dsh-lmc-config
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command: ["/bin/bash"]
    args: ["-c", "sed -i \"s/ska-lmc-vm:10000/$TANGO_HOST/g\" ./config/sample_config.json && ./scripts/configure_lmc.sh --no-rootpass --config=./config/sample_config.json "]
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}
  containers:
  - name: dish-master
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "sleep infinity"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: ds-simulator
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/ds-simulator 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: dsctrl-simulator
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/dsctrl-simulator 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: lmc-logger
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/lmc-logger 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: pdu-manager
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "sleep infinity"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: pdu-simulator
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/pdu-simulator 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: rx-simulator
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/rx-simulator 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: spf-simulator
    image: "{{ .Values.dshlmc.image.registry }}/{{ .Values.dshlmc.image.image }}:{{ .Values.dshlmc.image.tag }}"
    imagePullPolicy: {{ .Values.dshlmc.image.pullPolicy }}
    command:
       - sh
    args:
       - -c
       - "./bin/spf-simulator 1"
    env: {{ include "dsh-lmc-prototype.shared_enviroment" . | indent 2 }}

  - name: dsconfig
    image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
    imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
    env:

    command:
       - sh
    args:
       - -c
       - "sleep infinity"


{{- with .Values.dshlmc.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}