# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tangodb:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: 0.2.0
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

databaseds:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-cpp
    tag: 0.2.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

itango:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: 0.2.1
    pullPolicy: IfNotPresent

tangotest:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 0.2.1
    pullPolicy: IfNotPresent

jive:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 0.2.1
    pullPolicy: IfNotPresent

logviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: 0.2.1
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
