# Default values for csp-proto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

csplmc:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mid-csp-lmc
    tag: 0.3.0
    pullPolicy: IfNotPresent

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: latest
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
